server:
  port: 8080

spring:
  data:
    redis:
      host: 118.31.36.179
      port: 6379
      password: linlin
      database: 0
      timeout: 3000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 3000
          test-on-borrow: true
          test-while-idle: true
     
  jackson:
    property-naming-strategy: SNAKE_CASE  # 确保字段名匹配
    default-property-inclusion: non_null  # 忽略空字段
  datasource:
    hikari:
      maximum-pool-size: 50  
      connection-timeout: 2000  
      idle-timeout: 60000  
      max-lifetime: 120000  
      leak-detection-threshold: 5000
      minimum-idle: 5
      validation-timeout: 3000
      connection-test-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.36.179:3306/shopdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: api
    password: linlin
  jpa:
    hibernate:
      ddl-auto: validate  # 改为验证模式
    generate-ddl: false    # 禁用自动生成
    show-sql: false
    
    open-in-view: false
    properties:
      hibernate:
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true
        generate_statistics: false
        session.events.log.LOG_QUERIES_SLOWER_THAN_MS: 100

  

  rocketmq:
    name-server: 118.31.36.179:9876
    producer:
      group: default-group
    # access-key: your-access-key
    # secret-key: your-secret-key

  jwt:
    secret: "xianzaishierlingerwunainsiyueershiliurixingqiliuxiawushisandianwushiqifen" # Valid Base64 string
    expiration: 86400000  # 24 hours in milliseconds

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.apiservice.entity

sms:
  code:
    expire-time: 300  # 5分钟有效期

logging:
  level:
    io.lettuce.core: DEBUG


    

