server:
  port: 8080

spring:
  datasource:
    hikari:
      leak-detection-threshold: 2000
      maximum-pool-size: 50
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 300000
      max-lifetime: 600000
      validation-timeout: 3000
      connection-test-query: SELECT 1
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://118.31.36.179:3306/shopdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&autoReconnect=true
    username: api
    password: linlin
  jpa:
    hibernate:
      ddl-auto: update  # 每次启动清空并重建表结构
    show-sql: true
    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        jdbc.batch_size: 50
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true

  redis:
    host: 118.31.36.179
    port: 6379
    password: linlin
    database: 0

  rocketmq:
    name-server: 118.31.36.179:9876
    producer:
      group: default-group
    # access-key: your-access-key
    # secret-key: your-secret-key

  jwt:
    secret: "xianzaishierlingerwunainsiyueershiliurixingqiliuxiawushisandianwushiqifen" # Valid Base64 string
    expiration: 86400000  # 24 hours in milliseconds

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.apiservice.entity


    

