name: Simple Java Deploy

on:
  push:
    branches: [ main ]  # 仅 main 分支触发

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 代码检出
      - uses: actions/checkout@v4

      # 2. 设置 JDK 环境
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'


      # 3. Maven 打包
      - run: mvn clean package -DskipTests  # 跳过测试加快速度:ml-citation{ref="1,4" data="citationList"}

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }} # 服务器地址
          username: ${{ secrets.SERVER_USERNAME }} # 服务器用户名，通常是部署用户
          key: ${{ secrets.SERVER_PRIVATE_KEY }} # 私钥内容，存储在GitHub Secrets中
          script: |  # 执行部署脚本，例如停止旧服务，启动新服务等
            cd /path/to/your/app  # 切换到应用目录
            git pull origin main  # 拉取最新代码，根据您的分支名修改
            # 停止旧服务，启动新服务等操作...
            sudo systemctl restart your-service-name
